### ISSUE TITLE
DefaultCSVFormat, CSVFormat and TSVFormat are not serializable

### ISSUE THREAD

**Issue by dgomesbr** [tototoshi/scala-csv#42]
Hey @tototoshi,

I was learning and poking around with Spark, I've decided to use a csv parser by copying some of the code from here (https://github.com/softwaremill/vote-counter/blob/master/src/main/scala/com/softwaremill/votecounter/voting/ResultsToCsvTransformer.scala) to my own repo and trying to apply `csvWriter.toCsvString` to some RDDs:

```
Exception in thread "main" org.apache.spark.SparkException: Task not serializable
	at org.apache.spark.util.ClosureCleaner$.ensureSerializable(ClosureCleaner.scala:166)
	at org.apache.spark.util.ClosureCleaner$.clean(ClosureCleaner.scala:158)
	at org.apache.spark.SparkContext.clean(SparkContext.scala:1623)
	at org.apache.spark.rdd.RDD.map(RDD.scala:286)
	at com.diegomagalhaes.spark.RecomendationApp$.main(RecomendationApp.scala:68)
	at com.diegomagalhaes.spark.RecomendationApp.main(RecomendationApp.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.io.NotSerializableException: com.diegomagalhaes.spark.RecomendationApp$$anon$1
Serialization stack:
	- object not serializable (class: com.diegomagalhaes.spark.RecomendationApp$$anon$1, value: com.diegomagalhaes.spark.RecomendationApp$$anon$1@2e34384c)
	- field (class: com.diegomagalhaes.spark.LiteCsvWriter, name: com$diegomagalhaes$spark$LiteCsvWriter$$format, type: interface com.github.tototoshi.csv.CSVFormat)
	- object (class com.diegomagalhaes.spark.LiteCsvWriter, com.diegomagalhaes.spark.LiteCsvWriter@2b556bb2)
	- field (class: com.diegomagalhaes.spark.RecomendationApp$$anonfun$4, name: csvWriter$1, type: class com.diegomagalhaes.spark.LiteCsvWriter)
	- object (class com.diegomagalhaes.spark.RecomendationApp$$anonfun$4, <function1>)
	at org.apache.spark.serializer.SerializationDebugger$.improveException(SerializationDebugger.scala:38)
	at org.apache.spark.serializer.JavaSerializationStream.writeObject(JavaSerializer.scala:47)
	at org.apache.spark.serializer.JavaSerializerInstance.serialize(JavaSerializer.scala:80)
	at org.apache.spark.util.ClosureCleaner$.ensureSerializable(ClosureCleaner.scala:164)
	... 10 more
```

As you can see in the stacktrace the only problem is ``` field (class: com.diegomagalhaes.spark.LiteCsvWriter, name: com$diegomagalhaes$spark$LiteCsvWriter$$format, type: interface com.github.tototoshi.csv.CSVFormat)```

for the code
```scala
implicit val csvFormat = new DefaultCSVFormat{
    override val delimiter: Char = ','
    override val quoting: Quoting = QUOTE_ALL
  }

//...
collectRecords(visitData).map( x => csvWriter toCsvString List(x._1, x._2, x._3, x._4, x._5))
```

That is easily resolved by adding the ```Serializable``` trait to the ```DefaultCSVFormat``` as:

```scala
implicit val csvFormat = new DefaultCSVFormat with Serializable{
    override val delimiter: Char = ','
    override val quoting: Quoting = QUOTE_ALL
  }
```

Is it the intended behavior to have those class not Serializable? if not can we put just make then?

Thanks,

Diego

**Comment by tototoshi** [comment]
I have not thought there is such a use-case that `CSVFormat` need to be `Serializable`.
However, There is no problem to override and append `with Serializable`. Please feel free to do that.

**Comment by dgomesbr** [comment]
oh, thanks did that. just pushed to see if it's incorporated to the codebase. Feel free to close and deny it.

Thanks again for the promptly response.
