### ISSUE TITLE
Not compatible with scala 2.11.4 version. 

### ISSUE THREAD

**Issue by harmeetsingh0013** [tototoshi/scala-csv#43]
I am using these libraries with scala 2.11.4 version, and got an exception : 
```
Cannot invoke the action, eventually got an error: java.lang.RuntimeException: j
ava.lang.NoClassDefFoundError: scala/collection/GenTraversableOnce$class
17:02 TD-Tube [play-akka.actor.default-dispatcher-5] ERROR application [Line-No:
141] -

! @6m5il5p93 - Internal server error, for (POST) [/users-csv] ->

play.api.Application$$anon$1: Execution exception[[RuntimeException: java.lang.N
oClassDefFoundError: scala/collection/GenTraversableOnce$class]]
        at play.api.Application$class.handleError(Application.scala:296) ~[play_
2.11-2.3.8.jar:2.3.8]
        at play.api.DefaultApplication.handleError(Application.scala:402) [play_
2.11-2.3.8.jar:2.3.8]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun
$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [play_2.11-2.3.8.jar:
2.3.8]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun
$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [play_2.11-2.3.8.jar:
2.3.8]
        at scala.Option.map(Option.scala:145) [scala-library-2.11.4.jar:na]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrE
lse(PlayDefaultUpstreamHandler.scala:320) [play_2.11-2.3.8.jar:2.3.8]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrE
lse(PlayDefaultUpstreamHandler.scala:316) [play_2.11-2.3.8.jar:2.3.8]
```
After searching on google, we need to downgrade our scala version, This is difficult for me. Is there another way, to use with 2.11.4 ?

**Comment by tototoshi** [comment]
Can you show me your build.sbt?
