### ISSUE TITLE
MalformedCSVException when last word ends with the collons

### ISSUE THREAD

**Issue by maksimu** [tototoshi/scala-csv#46]
I have the following code to read CSV file:

    val reader = CSVReader.open(csvFile)
    reader.all()

Works with:
```
  1, 2, 3, 4, 5
  a, b, c, d, e
  "a a", b, c, d, e
```
but failing with:
```
  1, 2, 3, 4, 5
  a, b, c, d, e
  "a a", b, c, d, "e"
```
Getting following error:
```
  "a a", b, c, d, "e"
  com.github.tototoshi.csv.MalformedCSVException: "a a", b, c, d, "e"
```

**Comment by tototoshi** [comment]
```
scala> new CSVParser(defaultCSVFormat)
res0: com.github.tototoshi.csv.CSVParser = com.github.tototoshi.csv.CSVParser@e7f4813

scala> res0.parseLine(""""a a", b, c, d, "e"""")
com.github.tototoshi.csv.MalformedCSVException: "a a", b, c, d, "e"
  at com.github.tototoshi.csv.CSVParser$.parse(CSVParser.scala:129)
  at com.github.tototoshi.csv.CSVParser.parseLine(CSVParser.scala:291)
  ... 43 elided

scala> res0.parseLine(""""a a", b, c, d,"e"""")
res4: Option[List[String]] = Some(List(a a,  b,  c,  d, e))
```

CSV doesn't ignore whitespace. For the parser, the last field is not 'e' and it starts with a whitespace. Double quotation is not the special character in this case and shoule be escaped like the following.

```
scala> res0.parseLine(""""a a", b, c, d, ""e""""")
res5: Option[List[String]] = Some(List(a a,  b,  c,  d,  "e"))
```
