### ISSUE TITLE
Error during parsing of csv string with escaped  HTML

### ISSUE THREAD

**Issue by dserdyuk** [tototoshi/scala-csv#65]
Input string: 
"481234998931247105","Sleep pattern has vanished for summer","2014-06-23 17:38:59.0","<a href=\"http://twitter.com/download/android\" rel=\"nofollow\">Twitter for Android</a>","en","-1","false","false","false","false","0","0","-1","-1","","-1.0","-1.0","320096279","anna","_enocenip","I like the woods","en","Devon","false","107","69","306","321","1","2011-06-19 02:00:14.0","London"

It works on version 0.8.0 for scala 2.10
```
Caused by: com.github.tototoshi.csv.MalformedCSVException: Malformed Input!: Some("481235003678806016","RT @slao_: can I not SIT AT HOME FOR THE FIRST MONTH OF SUMMER","2014-06-23 17:39:00.0","<a href=\"http://twitter.com/download/iphone\" rel=\"nofollow\">Twitter for iPhone</a>","en","481232629744668674","false","false","true","false","0","0","-1","-1","","-1.0","-1.0","437153249","Patrick","pbates243","My hands are smaller than yours)
	at com.github.tototoshi.csv.CSVReader.parseNext$1(CSVReader.scala:36) ~[scala-csv_2.11-1.2.2.jar:1.2.2]
	at com.github.tototoshi.csv.CSVReader.readNext(CSVReader.scala:51) ~[scala-csv_2.11-1.2.2.jar:1.2.2]
	at com.github.tototoshi.csv.CSVReader$$anonfun$toStream$1.apply(CSVReader.scala:88) ~[scala-csv_2.11-1.2.2.jar:1.2.2]
	at com.github.tototoshi.csv.CSVReader$$anonfun$toStream$1.apply(CSVReader.scala:88) ~[scala-csv_2.11-1.2.2.jar:1.2.2]
	at scala.collection.immutable.Stream$.continually(Stream.scala:1279) ~[scala-library-2.11.7.jar:na]
	at com.github.tototoshi.csv.CSVReader.toStream(CSVReader.scala:88) ~[scala-csv_2.11-1.2.2.jar:1.2.2]
	at com.github.tototoshi.csv.CSVReader.all(CSVReader.scala:91) ~[scala-csv_2.11-1.2.2.jar:1.2.2]
```

**Comment by dserdyuk** [comment]
CSV turned out to be malformed. I contains \n at some comment columns. Closing the issue.
